[build-system]
requires = ["scikit-build-core", "nanobind", "pylmcf>=0.9.10"]
build-backend = "scikit_build_core.build"

[project]
name = "wnet"
version = "0.9.13"
description = "Tools for calculation of Wasserstein metric between distributions based on Network Flow algorithm"
authors = [{ name="Michał Startek", email="michal.startek@mimuw.edu.pl" }]
maintainers = [{ name="Michał Startek", email="michal.startek@mimuw.edu.pl" }]
dependencies = ["pylmcf>=0.9.10", "numpy"]
license = "MIT"
license-files = ["LICENCE"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Development Status :: 4 - Beta",

]
keywords = ["Wasserstein", "Optimal Transport", "Network Flow", "Earth Mover's Distance"]
requires-python = ">=3.9"

[project.urls]
"Homepage" = "https://github.com/michalsta/wnet"
"Repository" = "https://github.com/michalsta/wnet.git"

[project.optional-dependencies]
extras = ["networkx", "matplotlib"]
pytest = ["pytest"]

[tool.scikit-build.sdist]
exclude = [
    "tests/",
    "dist/",
    ".github/",
    ".vscode/",
    ".pytest_cache/",
    "src/wnet/__pycache__/",
    "src/wnet/cpp/wnet/a.out",
    "src/wnet/cpp/wnet/a.out.dSYM/",
    "df.py",
    "example.py",
    "reinstall.sh",
    ".coverage",
]
# [tool.scikit-build]
# cmake.build-type = "Debug"

[tool.pytest.ini_options]
markers = [
    "long: marks tests as long-running (deselect with '-m \"not long\"')",
]
addopts = "-m 'not long'"
